name: mistlock-gcp-firebase-cloud-functions

services:
  dev:
    image: mcr.microsoft.com/devcontainers/python:3.12-bookworm
    volumes:
      - .:/app:cached
    working_dir: /app
    command: sleep infinity
