services:
  postgres:
    image: postgres:15
    container_name: gcp_postgres_local
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mve_db
    volumes:
      - gcp_postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

  dev:
    image: mcr.microsoft.com/devcontainers/python:3.12-bookworm
    volumes:
      - .:/app:cached
    working_dir: /app
    network_mode: host
    command: sleep infinity

volumes:
  gcp_postgres_data:
