name: mistlock-azure-sql-writer

services:
  azure-sql-edge:
    image: mcr.microsoft.com/azure-sql-edge:latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${SQL_PASSWORD}
    volumes:
      - sql_data:/var/opt/mssql

  dev:
    image: mcr.microsoft.com/devcontainers/python:3.12-bookworm
    volumes:
      - .:/app:cached
    working_dir: /app
    command: sleep infinity

volumes:
  sql_data:
