services:
  localstack:
    image: localstack/localstack:4.14
    container_name: localstack_aws_step_functions
    ports:
      - "4566:4566"
    environment:
      - SERVICES=lambda,s3,dynamodb,iam,stepfunctions
      - DEFAULT_REGION=us-east-1
    volumes:
      - "localstack_data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  localstack_data:
