services:
  localstack:
    image: localstack/localstack
    container_name: localstack_local
    ports:
      - "4566:4566"
    environment:
      - SERVICES=lambda,s3,iam,cloudformation,logs
      - DEBUG=0
    volumes:
      - localstack_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

  dev:
    image: mcr.microsoft.com/devcontainers/python:3.12-bookworm
    volumes:
      - .:/app:cached
    working_dir: /app
    network_mode: host
    environment:
      - AWS_PROFILE=localstack
    command: sleep infinity

volumes:
  localstack_data:
