name: mistlock-aws-s3-minio

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  dev:
    image: mcr.microsoft.com/devcontainers/python:3.12-bookworm
    network_mode: host
    depends_on:
      - minio
    volumes:
      - .:/app:cached
    working_dir: /app
    command: sleep infinity

volumes:
  minio_data:
