services:
  postgres:
    image: postgres:latest
    container_name: postgres_local
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  dev:
    image: mcr.microsoft.com/devcontainers/python:3.12-bookworm
    volumes:
      - .:/app:cached
    working_dir: /app
    network_mode: host
    command: sleep infinity

volumes:
  postgres_data:
