metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
db_engine = "sqlite"

replication_factor = 1

rpc_bind_addr = "[::]:3901"
rpc_public_addr = "127.0.0.1:3901"
rpc_secret = "7a29bd9800de8560712da6f0eeec8b689cc8155884554f8ac45730a27fe12307"

[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:3900"
root_domain = ".s3.garage.localhost"

[s3_web]
bind_addr = "[::]:3902"
root_domain = ".web.garage.localhost"
index = "index.html"

[k2v_api]
api_bind_addr = "[::]:3904"

[admin]
api_bind_addr = "[::]:3903"
admin_token = "VXCYTa98je90Zxwl/xXf7O6UW9Um6OE+hyXcz72dLiU="
metrics_token = "G0WmW6BNjMDrK7NloX1xeXWVatqPQKigBpMdxKhj1v8="
