[garage-s3]
type = s3
provider = Other
access_key_id = GK32eef747151e54004044fc41
secret_access_key = 22ae6922c1d80b12feca83718f2dc05f84b1781b9013be53be1817edfcbf49ff
endpoint = http://localhost:3900
region = garage
location_constraint = garage
acl = private

