apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: blob-input
# Dapr monitors Azurite for new blobs
spec:
  type: bindings.azure.blobstorage
  version: v1
  metadata:
  - name: connectionString
    value: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;"
  - name: container
    value: "inbound"
  - name: decodeBase64
    value: "false"
  - name: createContainerIfNotExists
    value: "true"
