### Call get_secret with admin
GET {{baseUrl}}/get_secret?username=admin

### Call get_secret with denied user
GET {{baseUrl}}/get_secret?username=guest

### (Debug mode) Call get_secret with admin
GET {{debugBaseUrl}}/get_secret?username=admin

### (Debug mode) Call get_secret with denied user
GET {{debugBaseUrl}}/get_secret?username=guest