services:
  mongo:
    image: mongo:8
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongodb_data:/data/db

  dev:
    image: mcr.microsoft.com/devcontainers/python:3.12-bookworm
    container_name: dev
    network_mode: host
    depends_on:
      - mongo
    volumes:
      - .:/app:cached
    working_dir: /app
    command: sleep infinity

volumes:
  mongodb_data:
