services:
  localstack:
    image: localstack/localstack:4.14
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,lambda,dynamodb,iam,cloudformation,logs
      - DEBUG=0
    volumes:
      - localstack_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

  dev:
    image: mcr.microsoft.com/devcontainers/python:3.12-bookworm
    volumes:
      - .:/workspaces/aws-dynamo-db:cached
    network_mode: host
    command: sleep infinity

volumes:
  localstack_data:
