name: CI

on:
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: "3.12"

      - name: Install Project Dependencies
        run: uv sync

      - name: Install Dev Containers CLI
        run: |
          chmod +x ./scripts/setup-tests.sh
          ./scripts/setup-tests.sh

      - name: Run MVE Tests
        run: uv run pytest -v -s tests/
        env:
          PYTHONPATH: .
